<?php /* Template Name: Partners Page Template */ get_header();
$FrontPage = get_option('page_on_front');
$topImage = get_field('inside_top_image'); ?>
	<main role="main">



				<section id="map" >
					<!--************************map main**************************-->
				  <!--map-->
				   <div class="partner-padd">
							  <div class="wrapper width-grid" style="margin-top:120px;">
								<!--map picture-->
								<div class="nomap-desktop">

							  <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="https://localhost:8081/npm/wp-content/themes/npm/img/MapGifFix.gif" usemap="#image-map">

<map name="image-map">
    <area target="_top" onclick="myFunctionnAMERICA()" alt="N.AMERICA" title="N.AMERICA" href="javascript:void(0);" coords="8,39,311,245" shape="rect">
    <area target="_top" onclick="myFunctionsAMERICA()" alt="S.AMERICA" title="S.AMERICA" href="javascript:void(0);" coords="14,248,313,456" shape="rect">
    <area target="_top" onclick="myFunctionAFRICA()" alt="AFRICA" title="AFRICA" href="javascript:void(0);" coords="633,420,329,176" shape="rect">
    <area target="_top" onclick="myFunctionEUROPE()" alt="EUROPE" title="EUROPE" href="javascript:void(0);" coords="313,39,643,174" shape="rect">
    <area target="_top" onclick="myFunctionASIA()" alt="ASIA" title="ASIA" href="javascript:void(0);" coords="645,12,933,311" shape="rect">
    <area target="_top" onclick="myFunctionAUSTR()" alt="AUSTRALIA" title="AUSTRALIA" href="javascript:void(0);" coords="934,257,1177,455" shape="rect">
</map>






								</div>
								<div class="nomap-mobile">
							   <img src="<?php  echo get_template_directory_uri(); ?>/img/MapMobileGifFix.gif" alt="Logo" >
							   </div>
								  <?php if (have_rows('project_map_color')) : while (have_rows('project_map_color')) : the_row(); ?>
								 	  <!--s amerika-->
								 			   <div class="row">
								 			 <div class="col-5">
								 				 <div class="center cursor-pointer ">
													 <a class="btn  usa" data-toggle="modal" data-target="#exampleModal">
													 <!--img  src="<?php the_sub_field('icon_map') ?>"-->
								 					<!--	 <p  class="text-grid-tab text-days"><?php //the_sub_field('title_map1') ?></p>-->
													 </a>
								 				 </div>
  														<!-- Modal -->
  														<div class="modal fade" id="exampleModal-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel-close" aria-hidden="true">
  														  <div class="modal-dialog" role="document">
  														    <div class="modal-content padding1">
  														      <div class="modal-body">
																  <!--USA-->
														  <?php if (have_rows('popup_details')) : while (have_rows('popup_details')) : the_row(); ?>
																		<div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
																		  <div class="col-md-4 col-12 align-self-center">
																				  <img class="map-height" src="<?php the_sub_field('distributername') ?>">
																		  </div>
																		   <div class="col-md-8 col-12" >
																		   <div class="center cursor-pointer scroll-modal">
																			<p class="text-left" class=""><?php the_sub_field('description_popup') ?></p>
																		   </div>
																		   </div>
																   </div>
														<?php endwhile; else: endif; ?>
  														      </div>
  														    </div>
  														  </div>
  														</div>
															<!-- Modal -->
								 				 </div>
								    <!--test  pomenat map-->



								 		   <!--Europe-->
								 			 <div class="col-5 no-padding ">
												<!--China-->
												 <div class="center cursor-pointer ">
													<a class="btn  china2" data-toggle="modal" data-target="#exampleModal12">
													<!--img  src="<?php the_sub_field('icon_map') ?>"-->
											<!--			 <p class="text-grid-tab">CHINA</p>-->
													</a>
												</div>
													   <!-- Modal -->
													   <div class="modal fade" id="exampleModal12-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel12-close" aria-hidden="true">
														 <div class="modal-dialog" role="document">
														   <div class="modal-content padding2">
														 <div class="modal-body">
													<?php if (have_rows('popup_details_china')) : while (have_rows('popup_details_china')) : the_row(); ?>
																		   <!--row3 -->
																	   <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
																		 <div class="col-md-4 col-12 align-self-center">
																				 <img class="map-height" src="<?php the_sub_field('distributername') ?>">
																		 </div>
																		  <div class="col-md-8 col-12" >
																		  <div class="center cursor-pointer scroll-modal">
																		   <p class="text-left"><?php the_sub_field('description_popup') ?></p>
																		  </div>
																		  </div>
																  </div>
													   <?php endwhile; else: endif; ?>
															 </div>
														   </div>
														 </div>
													   </div>
														   <!-- Modal -->

														   <!--INDIA-->
						   								 <div class="center cursor-pointer ">
						   									<a class="btn india no-maptitle" data-toggle="modal" data-target="#exampleModal13">
						   									<!--img  src="<?php the_sub_field('icon_map') ?>"-->
						   										<!-- <p class="text-grid-tab">INDIA</p>-->
						   									</a>
						   								</div>
						   									   <!-- Modal -->
						   									   <div class="modal fade" id="exampleModal13-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel13-close" aria-hidden="true">
						   										 <div class="modal-dialog" role="document">
						   										   <div class="modal-content padding3">
						   											 <div class="modal-body">
						   							 <?php if (have_rows('popup_details_india')) : while (have_rows('popup_details_india')) : the_row(); ?>
						   													   <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
						   														 <div class="col-md-4 col-12 align-self-center">
						   																 <img class="map-height" src="<?php the_sub_field('distributername') ?>">
						   														 </div>
						   														  <div class="col-md-8 col-12" >
						   														  <div class="center cursor-pointer scroll-modal">
						   														   <p class="text-left"><?php the_sub_field('description_popup') ?></p>
						   														  </div>
						   														  </div>
						   												  </div>
						   									   <?php endwhile; else: endif; ?>
						   											 </div>
						   										   </div>
						   										 </div>
						   									   </div>
						   										   <!-- Modal -->

													<!-- / popup INDIA-->
												</div>
								 	   </div>

								 	   <div class="row">
								 		   <!--n amerika-->
								 		  <div class="col-5  text-left" style="">
								 				 <p class="text-grid-tab"><?php //the_sub_field('title_map2') ?></p>
								 		  </div>
								 		   <!--afrika-->
								 		  <div class="col-6 margin-map ">
											   <!--icon click  to Germany popup-->
			   								 <div class="center cursor-pointer ">
			   									<a class="btn germany " data-toggle="modal" data-target="#exampleModal14">
			   									<!--img  src="<?php the_sub_field('icon_map') ?>"-->
			   										<!-- <p class="text-grid-tab">Germany</p>-->
			   									</a>
			   								</div>
			   									   <!-- Modal -->
			   									   <div class="modal fade" id="exampleModal14-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel14-close" aria-hidden="true">
			   										 <div class="modal-dialog" role="document">
			   										   <div class="modal-content padding4">
			   											 <div class="modal-body">
			   									 <?php if (have_rows('popup_details_germany')) : while (have_rows('popup_details_germany')) : the_row(); ?>
			   	  													   <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
			   														 <div class="col-md-4 col-12 align-self-center">
			   																 <img class="map-height" src="<?php the_sub_field('distributername') ?>">
			   														 </div>
			   														  <div class="col-md-8 col-12" >
			   														  <div class="center cursor-pointer scroll-modal">
			   														   <p  class="text-left"><?php the_sub_field('description_popup') ?></p>
			   														  </div>
			   														  </div>
			   												  </div>
			   									   <?php endwhile; else: endif; ?>
			   											 </div>
			   										   </div>
			   										 </div>
			   									   </div>
			   										   <!-- Modal -->

										<!-- / popup Germany-->

										<!--icon click THE NETHERLANDS popup-->
									  <div class="center cursor-pointer ">
										 <a class="btn niderlandy " data-toggle="modal" data-target="#exampleModal15">
										 <!--img  src="<?php the_sub_field('icon_map') ?>"-->
											 <!-- <p class="text-grid-tab">THE NETHERLANDS</p>-->
										 </a>
									 </div>
											<!-- Modal -->
											<div class="modal fade" id="exampleModal15-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel15-close" aria-hidden="true">
											  <div class="modal-dialog" role="document">
												<div class="modal-content padding5">
												  <div class="modal-body">
										 <?php if (have_rows('popup_details_niderlandy')) : while (have_rows('popup_details_niderlandy')) : the_row(); ?>
															<div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
															  <div class="col-md-4 col-12 align-self-center">
																	  <img class="map-height" src="<?php the_sub_field('distributername') ?>">
															  </div>
															   <div class="col-md-8 col-12" >
															   <div class="center cursor-pointer scroll-modal">
																<p style="text-align:left" class=""><?php the_sub_field('description_popup') ?></p>
															   </div>
															   </div>
													   </div>
											<?php endwhile; else: endif; ?>
												  </div>
												</div>
											  </div>
											</div>
												<!-- Modal -->

								 <!-- / popup THE NETHERLANDS-->

								 <!--click icon popup THE Israel-->
								<div class="center cursor-pointer ">
								   <a class="btn israel " data-toggle="modal" data-target="#exampleModal16">
								   <!--img  src="<?php the_sub_field('icon_map') ?>"-->
									<!--	<p class="text-grid-tab">ISRAEL</p>-->
								   </a>
							   </div>
									  <!-- Modal -->
									  <div class="modal fade" id="exampleModal16-close" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel16-close" aria-hidden="true">
										<div class="modal-dialog" role="document">
										  <div class="modal-content padding6">
											<div class="modal-body">
										<?php if (have_rows('popup_details_israel')) : while (have_rows('popup_details_israel')) : the_row(); ?>
													  <div class="row tab-border popup-style" style="background-color:#2fc7f4; display:none">
														<div class="col-md-4 col-12 align-self-center">
																<img class="map-height" src="<?php the_sub_field('distributername') ?>">
														</div>
														 <div class="col-md-8 col-12" >
														 <div class="center cursor-pointer scroll-modal">
														  <p style="text-align:left" class=""><?php the_sub_field('description_popup') ?></p>
														 </div>
														 </div>
												 </div>
									  <?php endwhile; else: endif; ?>
											</div>
										  </div>
										</div>
									  </div>
										  <!-- Modal -->
						   <!-- / *********************popup THE Israel*******************-->
								 		 </div>
								 	</div>
								 		 <?php endwhile; else: endif; ?>
								<!--   <div style="margin: 0 auto">	<a href="/partners/" class="">MORE</a> </div>-->
								  <div class="clearfix"></div>
								<!--map-->

					  </div>
					</div>
				  <!--/ TAb 2-->
					  <!--**************************/map****************************-->
				</section>

<style>

.padding1 {
    margin-left: -52% !important;
}
.modal-dialog {
    max-width:868px !important;
}
.tab-border img {
	width: 330px;
}
.hsha{
	width: 100%;
}
.essha{
	width: 63%;
}
@media all and (max-width: 600px) {
	.essha{width: 100%;}
}
hr{
	/*width: 100%;*/
}
.cimnhg{
	margin: 10px 0 0 0;
}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script>
$(function() {
	/*sort*/
	var $list = $("#ALL");
	$list.children().detach().sort(function(a, b) {
		return $(a).text().localeCompare($(b).text());
	}).appendTo($list);
	/*sort*/
});
</script>

<section id="project_country">
<div class="row-space wrapper">
<div class="row center">
<div class="wrapper">

<ul class="nav nav-tabs" id="myTabs">
    <li class="nav-item nav-item-space active"><a class="nav-link active" data-toggle="tab" href="#ALL">ALL</a></li>
    <li class="nav-item nav-item-space"><a class="nav-link" data-toggle="tab" href="#ASIA">ASIA</a></li>
    <li class="nav-item nav-item-space"><a class="nav-link" data-toggle="tab" href="#AFRICA">AFRICA</a></li>
    <li class="nav-item nav-item-space"><a class="nav-link" data-toggle="tab" href="#AUSTRALIA">AUSTRALIA</a></li>
    <li class="nav-item nav-item-space"><a class="nav-link" data-toggle="tab" href="#EUROPE">EUROPE</a></li>
    <li class="nav-item nav-item-space"><a class="nav-link" data-toggle="tab" href="#nAMERICA">N.AMERICA</a></li>
    <li class="nav-item nav-item-space"><a class="nav-link" data-toggle="tab" href="#sAMERICA">S.AMERICA</a></li>
</ul>

<div class="tab-content">
    <div id="ALL" class="tab-pane fade show active">
		<!-- all -->
		<?php $i=$i;  if (have_rows('project_country_asia')) : while (have_rows('project_country_asia')) : the_row(); $i++; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay" onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img class="cimnhg" src="<?php the_sub_field('icon_country1') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p id="cnam" class="text-grid text-days"><?php the_sub_field('country1') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer1')) : while (have_rows('distributer1')) : the_row(); $o++; ?>
		<div class="row hsha">
			<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
			<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
				<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin: 0px 5px 0px 35px;" id="icos_<?php echo $i; ?>">
					<img  src="<?php the_sub_field('img') ?>">
				</div>
				<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
					<div class="center cursor-pointer">
						<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
					</div>
				</div>
			</div>
		</div>
		<hr />
		</div>


		<?php endwhile; else: endif; ?>
		</div>

		<?php endwhile; else: endif; ?>

		<?php $i=$i;  if (have_rows('project_country_africa')) : while (have_rows('project_country_africa')) : the_row(); $i++; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country2') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p id="cnam" class="text-grid text-days"><?php the_sub_field('country2') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer2')) : while (have_rows('distributer2')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>

		<?php $i=$i;  if (have_rows('project_country_australia_new')) : while (have_rows('project_country_australia_new')) : the_row(); $i++; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay" onclick="icon_shaytext3(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country6') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p id="cnam" class="text-grid text-days"><?php the_sub_field('country6') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>

		<?php $i=$i;  if (have_rows('project_country_europe')) : while (have_rows('project_country_europe')) : the_row(); $i++; ?>

		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country4') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p id="cnam" class="text-grid text-days"><?php the_sub_field('country4') ?></p>
		</div>
		</div>

		<?php $o=0;  if (have_rows('distributer4')) : while (have_rows('distributer4')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>


		</div>
		<?php endwhile; else: endif; ?>


		<?php $i=$i;  if (have_rows('project_country_n_america')) : while (have_rows('project_country_n_america')) : the_row(); $i++; ?>
		<?php //echo $i. '<br>'; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2  center">
		<div class="center cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country5') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3  center" style="margin: 10px 0 0 0;">
		<div class="text-left cursor-pointer">
		<p id="cnam" class="text-grid text-days"><?php the_sub_field('country5') ?></p>
		</div>
		</div>
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('distributer5') ?>">
		</div>
		<div class="col-md-5 col-12 no-padding tab-border hides" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('description5') ?></p>
		</div>
		</div>
		</div>
		<?php endwhile; else: endif; ?>


		<?php $i=$i;  if (have_rows('project_country_s_america_new')) : while (have_rows('project_country_s_america_new')) : the_row(); $i++; ?>
		<?php //echo $i. '<br>'; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shaytext2(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country6') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p id="cnam" class="text-grid text-days"><?php the_sub_field('country6') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>

		<?php $i=$i;  if (have_rows('project_country_s_america')) : while (have_rows('project_country_s_america')) : the_row(); $i++; ?>
		<?php //echo $i. '<br>'; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shaytext2(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country6') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p class="text-grid text-days"><?php the_sub_field('country6') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
		<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>
		<!-- all -->

    </div>
    <div id="ASIA" class="tab-pane fade">



		<?php $i=$i;  if (have_rows('project_country_asia')) : while (have_rows('project_country_asia')) : the_row(); $i++; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country1') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p class="text-grid text-days"><?php the_sub_field('country1') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer1')) : while (have_rows('distributer1')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>

    </div>
    <div id="AFRICA" class="tab-pane fade">



		<?php $i=$i;  if (have_rows('project_country_africa')) : while (have_rows('project_country_africa')) : the_row(); $i++; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country2') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p class="text-grid text-days"><?php the_sub_field('country2') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer2')) : while (have_rows('distributer2')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>





    </div>
    <div id="AUSTRALIA" class="tab-pane fade">

		<?php $i=$i;  if (have_rows('project_country_australia_new')) : while (have_rows('project_country_australia_new')) : the_row(); $i++; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shaytext3(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country6') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p class="text-grid text-days"><?php the_sub_field('country6') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>

    </div>
	<div id="EUROPE" class="tab-pane fade">


		<?php $i=$i;  if (have_rows('project_country_europe')) : while (have_rows('project_country_europe')) : the_row(); $i++; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"   onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country4') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p class="text-grid text-days"><?php the_sub_field('country4') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer4')) : while (have_rows('distributer4')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>





    </div>
	<div id="nAMERICA" class="tab-pane fade">




		<?php $i=$i;  if (have_rows('project_country_n_america')) : while (have_rows('project_country_n_america')) : the_row(); $i++; ?>
		<?php //echo $i. '<br>'; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="center cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country5') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p class="text-grid text-days"><?php the_sub_field('country5') ?></p>
		</div>
		</div>
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('distributer5') ?>">
		</div>
		<div class="col-md-5 col-12 no-padding tab-border hides" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('description5') ?></p>
		</div>
		</div>
		</div>
		<?php endwhile; else: endif; ?>


		<?php $i=$i;  if (have_rows('project_country_s_america_new')) : while (have_rows('project_country_s_america_new')) : the_row(); $i++; ?>
		<?php //echo $i. '<br>'; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shaytext2(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country6') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p class="text-grid text-days"><?php the_sub_field('country6') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
			<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>
    </div>
	<div id="sAMERICA" class="tab-pane fade">


		<?php $i=$i;  if (have_rows('project_country_s_america')) : while (have_rows('project_country_s_america')) : the_row(); $i++; ?>
		<?php //echo $i. '<br>'; ?>
		<div class="row tab-border icon_shay<?php echo $i;?>" id="icon_shay"  onclick="icon_shaytext2(<?php echo $i; ?>)" date="<?php echo $i; ?>">
		<div class="col-md-1 col-2 align-self-center center">
		<div class="text-left cursor-pointer">
		<img  class="cimnhg" src="<?php the_sub_field('icon_country6') ?>">
		</div>
		</div>
		<div class="col-md-3 col-8 col-lg-3 align-self-center center">
		<div class="text-left cursor-pointer">
		<p class="text-grid text-days"><?php the_sub_field('country6') ?></p>
		</div>
		</div>
		<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
		<div class="row hsha">
		<div class="col-md-3 col-12 col-lg-3 align-self-center center"></div>
		<div class="col-md-9 col-12 col-lg-9 align-self-center center">
		<div class="row">
		<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin:0px 5px 0px 35px" id="icos_<?php echo $i; ?>">
		<img  src="<?php the_sub_field('img') ?>">
		</div>
		<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
		<div class="center cursor-pointer">
		<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
		</div>
		</div>
		</div>
		</div>
		</div>
		<hr />
		<?php endwhile; else: endif; ?>
		</div>
		<?php endwhile; else: endif; ?>




    </div>
  </div>
</div>
</div>
</div>
</div>
</section>


<script>
function myFunctionASIA() {
	$('.nav-tabs li a').removeClass('active show');
	$('.nav-tabs li:eq(1) a').tab('show');
	$('.nav-tabs li:eq(1) a').addClass('active show');
	$('#ASIA').removeClass('in');
	$('#ASIA').addClass('show');
	return true;
}
function myFunctionAFRICA() {
	$('.nav-tabs li a').removeClass('active show');
	$('.nav-tabs li:eq(2) a').tab('show');
	$('.nav-tabs li:eq(2) a').addClass('active show');
	$('#AFRICA').removeClass('in');
	$('#AFRICA').addClass('show');
	return true;
}
function myFunctionAUSTR() {
	$('.nav-tabs li a').removeClass('active show');
	$('.nav-tabs li:eq(3) a').tab('show');
	$('.nav-tabs li:eq(3) a').addClass('active show');
	$('#AUSTRALIA').removeClass('in');
	$('#AUSTRALIA').addClass('show');
	return true;
}
function myFunctionEUROPE() {
	$('.nav-tabs li a').removeClass('active show');
	$('.nav-tabs li:eq(4) a').tab('show');
	$('.nav-tabs li:eq(4) a').addClass('active show');
	$('#EUROPE').removeClass('in');
	$('#EUROPE').addClass('show');
	return true;
}
function myFunctionnAMERICA() {
	$('.nav-tabs li a').removeClass('active show');
	$('.nav-tabs li:eq(5) a').tab('show');
	$('.nav-tabs li:eq(5) a').addClass('active show');
	$('#nAMERICA').removeClass('in');
	$('#nAMERICA').addClass('show');
	return true;
}
function myFunctionsAMERICA() {
	$('.nav-tabs li a').removeClass('active show');
	$('.nav-tabs li:eq(6) a').tab('show');
	$('.nav-tabs li:eq(6) a').addClass('active show');
	$('#sAMERICA').removeClass('in');
	$('#sAMERICA').addClass('show');
	return true;
}
//$('.nav-tabs li:eq(2) a').tab('show');
</script>



  				<!--**************************Filter with all country begin****************************-->
<?php /*
				<section id="project_map">
<!-- section begin-->

<div class="row center">
<div class="wrapper">
	<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
		<li class="nav-item nav-item-space">
		<a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">ALL</a></li>
		<li class="nav-item nav-item-space">
		<a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">ASIA</a></li>
		<li class="nav-item nav-item-space">
		<a class="nav-link" id="pills-profile-tab2" data-toggle="pill" href="#pills-profile2" role="tab" aria-controls="pills-profile2" aria-selected="false">AFRICA</a></li>
		<li class="nav-item nav-item-space">
		<a class="nav-link" id="pills-profile-tab3" data-toggle="pill" href="#pills-profile3" role="tab" aria-controls="pills-profile3" aria-selected="false">AUSTRALIA</a></li>
		<li class="nav-item nav-item-space">
		<a class="nav-link" id="pills-profile-tab4" data-toggle="pill" href="#pills-profile4" role="tab" aria-controls="pills-profile4" aria-selected="false">EUROPE</a></li>
		<li class="nav-item nav-item-space">
		<a class="nav-link" id="pills-profile-tab5" data-toggle="pill" href="#pills-profile5" role="tab" aria-controls="pills-profile5" aria-selected="false">N. AMERICA</a></li>
		<li class="nav-item nav-item-space">
		<a class="nav-link" id="pills-profile-tab6" data-toggle="pill" href="#pills-profile6" role="tab" aria-controls="pills-profile6" aria-selected="false">S. AMERICA</a></li>
	</ul>
<!---nav with cities-->
<div class="tab-content" id="pills-tabContent">
<!--TAb 1-->
<!--*******************tab 1*******************************-->
<div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab"> <!--nav--->
<!--info 1 for country 1-->
<div  style="margin-top:80px">
<div class=" row-space wrapper" >
<!---*********show All (country 1 Asia)************-->

<?php /*$i=0; if (have_rows('project_country_asia')) : while (have_rows('project_country_asia')) : the_row();$i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border"  id="icon_shay" onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2  align-self-center center">
<div class="center cursor-pointer">
<img  src="<?php the_sub_field('icon_country1') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country1') ?></p>
</div>
</div>
<div class="col-md-3 col-12 no-padding align-self-center tab-border hides" id="icos_<?php echo $i; ?>">
<img class="map-height" src="<?php the_sub_field('distributer1') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description1') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif;*/ ?>


<?php /*$i=$i;  if (have_rows('project_country_africa')) : while (have_rows('project_country_africa')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay" onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center" >
<div class="center cursor-pointer">
<img  src="<?php the_sub_field('icon_country2') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div>
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country2') ?></p>
</div>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer2') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description2') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif;*/ ?>


<?php /*$i=$i;  if (have_rows('project_country_australia')) : while (have_rows('project_country_australia')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay" onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="center cursor-pointer">
<img  src="<?php the_sub_field('icon_country3') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country3') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer3') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description3') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif;*/ ?>


<?php /*$i=$i;  if (have_rows('project_country_australia_new')) : while (have_rows('project_country_australia_new')) : the_row(); $i++; ?>

<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay" onclick="icon_shaytext3(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="text-left cursor-pointer">
<img  src="<?php the_sub_field('icon_country6') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country6') ?></p>
</div>
</div>

<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
<?php

?>
<div class="row">
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin: 0 5px 0 60px;" id="icos_<?php echo $i; ?>">
<img  src="<?php the_sub_field('img') ?>">
</div>
<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
</div>
</div>
</div>
<hr />
<?php endwhile; else: endif; ?>

</div>

<?php endwhile; else: endif; ?>

</div>
</div>

</div>




<?php /*$i=$i;  if (have_rows('project_country_europe')) : while (have_rows('project_country_europe')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay" onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="text-left cursor-pointer">
<img  src="<?php the_sub_field('icon_country4') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country4') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer4') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description4') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif;*/ ?>

<!---/ show All (country 4 Europe)-->

<!--*********************************N. America show All*****************************************-->

<?php /* רגיל
<?php $i=$i;  if (have_rows('project_country_australia')) : while (have_rows('project_country_australia')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay" onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="center cursor-pointer">
<img  src="<?php the_sub_field('icon_country3') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country3') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer3') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description3') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif; ?>

<!---/ show All (country 3 Australia)-->
*/ ?>
<?php /*
<div class="row tab-border" id="icon_shay" date="85">
<div class="col-md-1 col-2 align-self-center center"  onclick="icon_shay(85)">
<div class="text-left cursor-pointer">
<img  src="http://npmsite.goil.co.il/wp-content/uploads/2018/10/FLAG-41.png">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center" onclick="icon_shay(85)">
<div class="text-left cursor-pointer">
<p class="text-grid text-days">USA</p>
</div>
</div>
<div class="col-8 align-self-center no-padding tab-border hides" id="icos_85">

<?php $i=$i;  if (have_rows('project_country_n_america')) : while (have_rows('project_country_n_america')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>

<div class="row tab-border" id="icon_shay12" onclick="icon_shay12(<?php echo $i; ?>)" date="<?php echo $i; ?>">

<div class="col-md-1 col-2 align-self-center center">
<div class="text-left cursor-pointer">
<img src="<?php the_sub_field('icon_country5') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country5') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos12_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer5') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob12_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description5') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif; ?>

</div>
<!--div class="col-12 no-padding tab-border hides" id="icob_85">
<div class="center cursor-pointer">
<p class="text-grid-tab"></p>
</div>
</div-->

</div>
*/ ?>






<?php /*$i=$i;  if (have_rows('project_country_n_america')) : while (have_rows('project_country_n_america')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay" onclick="icon_shay(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="center cursor-pointer">
<img  src="<?php the_sub_field('icon_country5') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country5') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer5') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description5') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif;*/ ?>

<!---/ show All (country 3 Australia)-->




<!---/ show All (country 4 N. America)-->
<!--*********************************S. America show All  new*****************************************-->
<?php /*$i=$i;  if (have_rows('project_country_s_america_new')) : while (have_rows('project_country_s_america_new')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay" onclick="icon_shaytext2(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="text-left cursor-pointer">
<img  src="<?php the_sub_field('icon_country6') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country6') ?></p>
</div>
</div>
<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
<div class="row">
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin: 0 5px 0 60px;" id="icos_<?php echo $i; ?>">
<img  src="<?php the_sub_field('img') ?>">
</div>
<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
</div>
</div>
</div>
<hr />
<?php endwhile; else: endif; ?>
</div>

<?php endwhile; else: endif; ?>
<!---/ show All (country 4 S. America)-->
<!---/ show All (country 4 N. America)-->
<!--*********************************S. America show All*****************************************-->
<?php $i=$i;  if (have_rows('project_country_s_america')) : while (have_rows('project_country_s_america')) : the_row(); $i++; ?>

<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay" onclick="icon_shaytext(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="text-left cursor-pointer">
<img  src="<?php the_sub_field('icon_country6') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country6') ?></p>
</div>
</div>

<?php $o=0;  if (have_rows('distributer6')) : while (have_rows('distributer6')) : the_row(); $o++; ?>
<div class="row">
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides icos_<?php echo $i; ?>" style="margin: 0 5px 0 60px;" id="icos_<?php echo $i; ?>">
<img  src="<?php the_sub_field('img') ?>">
</div>
<div class="col-md-7 col-12 no-padding tab-border hides icob_<?php echo $i; ?>" id="icob_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('text') ?></p>
</div>
</div>
</div>
<hr />
<?php endwhile; else: endif; ?>
</div>
<?php endwhile; else: endif; ?>
<!---/ show All (country 4 S. America)-->
</div>
</div>
<!--- / end  *********show all  for countries**************-->
</div>
<!--nav end  --->
</div>
</div>
<!--- / end  *********show all  for countries**************-->
</div>
<!--nav end  --->
<!--***********************ASIA filter new***************************-->
<!--TAb 1   for countru ASIA-->
<div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
<?php  $FrontPage = get_option('page_on_front'); ?>
<div class="" style="margin-top:80px">
<div class="wrapper row-space" >
<!---country 1  row all-->
<?php $i=0; if (have_rows('project_country_asia')) : while (have_rows('project_country_asia')) : the_row();$i++; ?>
<!--row2 -->
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay2" onclick="icon_shay2(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2  align-self-center center">
<div class="center cursor-pointer">
<img  src="<?php the_sub_field('icon_country1') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">

<p class="text-grid text-days"><?php the_sub_field('country1') ?></p>

</div>
<div class="col-md-3 col-12 no-padding align-self-center tab-border hides" id="icos2_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer1') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob2_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description1') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif; ?>

<!---country 2  row all-->
</div>
</div>

</div>
<!--/ TAb 1-->
<!--************************tab 2 Africa filter**************************-->

<div class="tab-pane fade" id="pills-profile2" role="tabpanel" aria-labelledby="pills-profile-tab2">
<div class=" " style="margin-top:80px">
<div class="wrapper row-space">
<?php $i=$i;  if (have_rows('project_country_africa')) : while (have_rows('project_country_africa')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay3" onclick="icon_shay3(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center ">
<div class="center cursor-pointer">
<img  src="<?php the_sub_field('icon_country2') ?>">
</div>
</div>
<div class="col-md-3 col-lg-3 col-8 align-self-center center">
<div>
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country2') ?></p>
</div>
</div>
</div>
<div class="col-md-3  col-12 align-self-center no-padding tab-border hides" id="icos3_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer2') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob3_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description2') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif; ?>
</div>
</div>
<!-- / row 2-->
</div>
<!--/ TAb 2-->
<!--**********************Australia filter****************************-->
<!--TAb 3 Australia-->
<div class="tab-pane fade" id="pills-profile3" role="tabpanel" aria-labelledby="pills-profile-tab3">
<!---shedule 4-->
<?php  $FrontPage = get_option('page_on_front'); ?>
<div class="" style="margin-top:80px">
<div class="wrapper row-space" >
<?php $i=$i;  if (have_rows('project_country_australia')) : while (have_rows('project_country_australia')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay4" onclick="icon_shay4(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="center cursor-pointer">
<img  src="<?php the_sub_field('icon_country3') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country3') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos4_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer3') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob4_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description3') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif; ?>
</div>
</div>
</div>
<!--/ TAb 3-->
<!--**********************Europa filter****************************-->
<!--TAb 4  Europa-->
<div class="tab-pane fade" id="pills-profile4" role="tabpanel" aria-labelledby="pills-profile-tab4">
<div class="" style="margin-top:80px">
<div class="wrapper row-space" >
<?php $i=$i;  if (have_rows('project_country_europe')) : while (have_rows('project_country_europe')) : the_row(); $i++; ?>

<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay5" onclick="icon_shay5(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="text-left cursor-pointer">
<img  src="<?php the_sub_field('icon_country4') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country4') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos5_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer4') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob5_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description4') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif; ?>
</div>
</div> <!-- / row 4-->
</div><!--/ TAb 4-->

<!--TAb 5 N. America-->
<!--**********************N.America filter****************************-->
<div class="tab-pane fade" id="pills-profile5" role="tabpanel" aria-labelledby="pills-profile-tab5">
<div class="" style="margin-top:80px">
<div class="wrapper row-space" >
<?php $i=$i;  if (have_rows('project_country_n_america')) : while (have_rows('project_country_n_america')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay6" onclick="icon_shay6(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="text-left cursor-pointer">
<img  src="<?php the_sub_field('icon_country5') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country5') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos6_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer5') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob6_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description5') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif; ?>
</div>
</div>
</div><!--/ TAb 5-->


<!--**********************S.America filter TAb 6****************************-->

<div class="tab-pane fade" id="pills-profile6" role="tabpanel" aria-labelledby="pills-profile-tab6">
<div class="" style="margin-top:80px">
<div class="wrapper row-space" >
<?php $i=$i;  if (have_rows('project_country_s_america')) : while (have_rows('project_country_s_america')) : the_row(); $i++; ?>
<?php //echo $i. '<br>'; ?>
<div class="row tab-border" id="icon_shay7" onclick="icon_shay7(<?php echo $i; ?>)" date="<?php echo $i; ?>">
<div class="col-md-1 col-2 align-self-center center">
<div class="text-left cursor-pointer">
<img  src="<?php the_sub_field('icon_country6') ?>">
</div>
</div>
<div class="col-md-3 col-8 col-lg-3 align-self-center center">
<div class="text-left cursor-pointer">
<p class="text-grid text-days"><?php the_sub_field('country6') ?></p>
</div>
</div>
<div class="col-md-3 col-12 align-self-center no-padding tab-border hides" id="icos7_<?php echo $i; ?>">
<img  src="<?php the_sub_field('distributer6') ?>">
</div>
<div class="col-md-5 col-12 no-padding tab-border hides" id="icob7_<?php echo $i; ?>">
<div class="center cursor-pointer">
<p class="text-grid-tab"><?php the_sub_field('description6') ?></p>
</div>
</div>
</div>
<?php endwhile; else: endif; ?>
</div>
</div>
</div><!--/ TAb 6-->
</div>
<!-- / end filter-->
</div>
</div>

</section>
					                <!--/ filter countries-->

				</section>
*/ ?>

				<section id="strip9">
						<?php  get_template_part('template-parts/our-partners-template'); ?>
						<div class="clearfix"></div>
				</section>

	</main>

<script>

/*$('#icon_shay').click(function (e) {
	var xid = document.getElementById("icon_shay").getAttribute("date");
	document.getElementById('icos_' + xid).style.display = "block";
	document.getElementById('icob_' + xid).style.display = "block";
	//prlinexc
	//alert('asdasdasd');
	//
});*/

function icon_shay(id){
	$( "#icos_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}
function icon_shaytext(id){
	$( ".icos_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( ".icob_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}

function icon_shaytext2(id){
	$( ".icos_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( ".icob_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}
function icon_shaytext3(id){
	$( ".icos_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( ".icob_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}

function icon_shay2(id){
	$( "#icos2_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob2_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}
function icon_shay3(id){
	$( "#icos3_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob3_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}

function icon_shay4(id){
	$( "#icos4_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob4_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}

function icon_shay5(id){
	$( "#icos5_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob5_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}
function icon_shay6(id){
	$( "#icos6_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob6_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}
function icon_shay7(id){
	$( "#icos7_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob7_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}
function icon_shay12(id){
	$( "#icos12_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob12_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}
function icon_shay21(id){
	$( "#icos21_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob12_" + id ).toggle( "slow", function() {
      // Animation complete.
    });
}
/*$( "#icon_shay" ).click(function() {
	var xid = document.getElementById("icon_shay").getAttribute("date");
	$( "#icos_" + xid ).toggle( "slow", function() {
      // Animation complete.
    });
	$( "#icob_" + xid ).toggle( "slow", function() {
      // Animation complete.
    });
});*/
/*$('#icon_shay').click(function (e) {
	var xid = document.getElementById("icon_shay").getAttribute("date");
	document.getElementById('icos_' + xid).style.display = "block";
	document.getElementById('icob_' + xid).style.display = "block";
	//prlinexc
	//alert('asdasdasd');
	//
});*/

jQuery(document).ready(function($) {

  setTimeout(function () {
		$("div[class *= 'icon_shay']").on('click', function(event) {
			event.preventDefault();
			console.log('click');
			console.log($(this).attr("date"));
      var id = $(this).attr("date");

		  var icosz =	$(this).find(".icos_"+id);

		  var icobz =	$(this).find(".icob_"+id);

      $.each(icosz,function(index, el) {

				if($(el).hasClass('hides')){
					$(el).removeClass('hides');
				}
				else{
							$(el).addClass('hides');
				}

      });

			$.each(icobz,function(index, el) {

				if($(el).hasClass('hides')){
 					$(el).removeClass('hides');
 				}
 				else{
 							$(el).addClass('hides');
 				}
      });

 

		});

  }, 1000);


});

</script>

<?php get_footer(); ?>
